using Crpg.Module.Api.Models.Items;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1;
using TaleWorlds.ObjectSystem;

namespace Crpg.Module.GUI.Inventory;

public class ItemInfoTupleVM : ViewModel
{
    private string _categoryName = string.Empty;
    private string _valueText = string.Empty;
    private bool _isGoldVisible;
    private bool _isBrushOneVisible;
    private bool _isBrushTwoVisible;
    private bool _isBrushThreeVisible;
    private string _brushOne = string.Empty;
    private string _brushTwo = string.Empty;
    private string _brushThree = string.Empty;

    [DataSourceProperty]
    public string CategoryName
    {
        get => _categoryName;
        set => SetField(ref _categoryName, value, nameof(CategoryName));
    }

    [DataSourceProperty]
    public string ValueText
    {
        get => _valueText;
        set => SetField(ref _valueText, value, nameof(ValueText));
    }

    [DataSourceProperty]
    public bool IsGoldVisible
    {
        get => _isGoldVisible;
        set => SetField(ref _isGoldVisible, value, nameof(IsGoldVisible));
    }

    [DataSourceProperty]
    public bool IsBrushOneVisible
    {
        get => _isBrushOneVisible;
        set => SetField(ref _isBrushOneVisible, value, nameof(IsBrushOneVisible));
    }

    [DataSourceProperty]
    public bool IsBrushTwoVisible
    {
        get => _isBrushTwoVisible;
        set => SetField(ref _isBrushTwoVisible, value, nameof(IsBrushTwoVisible));
    }

    [DataSourceProperty]
    public bool IsBrushThreeVisible
    {
        get => _isBrushThreeVisible;
        set => SetField(ref _isBrushThreeVisible, value, nameof(IsBrushThreeVisible));
    }

    [DataSourceProperty]
    public string BrushOne
    {
        get => _brushOne;
        set => SetField(ref _brushOne, value, nameof(BrushOne));
    }

    [DataSourceProperty]
    public string BrushTwo
    {
        get => _brushTwo;
        set => SetField(ref _brushTwo, value, nameof(BrushTwo));
    }

    [DataSourceProperty]
    public string BrushThree
    {
        get => _brushThree;
        set => SetField(ref _brushThree, value, nameof(BrushTwo));
    }
}
