using Crpg.Module.Api.Models.Items;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated1;
using TaleWorlds.ObjectSystem;

namespace Crpg.Module.GUI.Inventory;

public class ItemInfoVm : ViewModel
{
    private ImageIdentifierVM _imageIdentifier;
    public ItemObject ItemObj { get; }

    public ItemInfoVm(ItemObject item)
    {
        // ItemObject _item = MBObjectManager.Instance.GetObject<ItemObject>("crpg_splittingmaul_v3_h3");
        ItemObj = item;
        _imageIdentifier = new ImageIdentifierVM(item);

    }

    [DataSourceProperty]
    public ImageIdentifierVM ImageIdentifier
    {
        get => _imageIdentifier;
        set => SetField(ref _imageIdentifier, value, nameof(ImageIdentifier));
    }

    [DataSourceProperty]
    public string Name => ItemObj.Name.ToString();

    [DataSourceProperty]
    public string Type => ItemObj.ItemType.ToString();

    [DataSourceProperty]
    public int Value => ItemObj.Value;

    [DataSourceProperty]
    public float Weight => ItemObj.Weight;


    [DataSourceProperty]
    public string ArmorStats
    {
        get
        {
            var armor = ItemObj.ArmorComponent;
            if (armor == null)
                return "N/A";
            return $"Head: {armor.HeadArmor}, Body: {armor.BodyArmor}, Arms: {armor.ArmArmor}, Legs: {armor.LegArmor}";
        }
    }

    [DataSourceProperty]
    public string WeaponStats
    {
        get
        {
            var weapon = ItemObj.PrimaryWeapon;
            if (weapon == null)
                return "N/A";
            return $"Damage: {weapon.SwingDamage}, Speed: {weapon.SwingSpeed}, Reach: {weapon.WeaponLength}";
        }
    }
}