# A script to help the workflow of balancers. It copies files to the game,
# run cRPG so they can run the export commands, and syncs files both ways:
# - repo XMLs -> game (so the game picks up your edits)
# - game XMLs + items.json -> repo (so you see exports/generations)

$ErrorActionPreference = "Stop"

if (-not $env:MB_CLIENT_PATH) {
    Write-Error "MB_CLIENT_PATH environment variable is not set."
    exit 1
}

$repoPath = Split-Path -Parent $PSScriptRoot
$repoModuleDataPath = Join-Path $repoPath "src\Module.Server\ModuleData"
$gameModulePath = Join-Path $env:MB_CLIENT_PATH "Modules\cRPG"
$gameModuleDataPath = Join-Path $gameModulePath "ModuleData"

$xmlFiles = @(
    "action_sets.xml",
    "action_types.xml",
    "collision_infos.xml",
    "crafting_pieces.xml",
    "crafting_templates.xml",
    "item_holsters.xml",
    "item_usage_sets.xml",
    "physics_materials.xml",
    "weapon_descriptions.xml",
    "items\arm_armors.xml",
    "items\banners.xml",
    "items\body_armors.xml",
    "items\head_armors.xml",
    "items\horses_and_others.xml",
    "items\leg_armors.xml",
    "items\shields.xml",
    "items\shoulder_armors.xml",
    "items\weapons.xml"
)

# Two-way sync pairs: repo path <-> game path.
$syncPairs = @()
foreach ($xml in $xmlFiles) {
    $syncPairs += @{
        RepoPath = Join-Path $repoModuleDataPath $xml
        GamePath = Join-Path $gameModuleDataPath $xml
        Name     = $xml
    }
}
# items.json is game -> repo only (generated by the game).
$itemsJsonGamePath = Join-Path $gameModuleDataPath "items.json"
$itemsJsonRepoPath = Join-Path $repoPath "data\items.json"

# Initial copy: repo -> game.
Write-Host "Copying XMLs to game: " -ForegroundColor Cyan -NoNewline
foreach ($pair in $syncPairs) {
    $gamePathParent = Split-Path $pair.GamePath -Parent
    if (-not (Test-Path $gamePathParent)) {
        New-Item -ItemType Directory -Path $gamePathParent -Force | Out-Null
    }
    Copy-Item $pair.RepoPath $pair.GamePath -Force
    Write-Host "$($pair.Name) " -NoNewline
}
Write-Host ""

# Snapshot last-write times for both sides.
$lastWriteRepo = @{}
$lastWriteGame = @{}
foreach ($pair in $syncPairs) {
    if (Test-Path $pair.RepoPath) {
        $lastWriteRepo[$pair.Name] = (Get-Item $pair.RepoPath).LastWriteTime
    }
    if (Test-Path $pair.GamePath) {
        $lastWriteGame[$pair.Name] = (Get-Item $pair.GamePath).LastWriteTime
    }
}
$lastWriteItemsJson = $null
if (Test-Path $itemsJsonGamePath) {
    $lastWriteItemsJson = (Get-Item $itemsJsonGamePath).LastWriteTime
}

$gameExePath = Join-Path $env:MB_CLIENT_PATH "bin\Win64_Shipping_Client\Bannerlord.exe"
$gameArgs = "_MODULES_*Native*Multiplayer*cRPG*_MODULES_ /multiplayer"
Write-Host "`nUse ALT+~ to open the console in-game, all commands start with crpg." -ForegroundColor Green
Write-Host "Two-way sync is active. Edit repo XMLs or use in-game export commands." -ForegroundColor Green
Write-Host "Starting Bannerlord..." -ForegroundColor Green
$process = Start-Process -FilePath $gameExePath -ArgumentList $gameArgs -WorkingDirectory (Split-Path $gameExePath -Parent) -PassThru

while (-not $process.HasExited) {
    foreach ($pair in $syncPairs) {
        # Repo -> Game: user edited a XML in the repo.
        if (Test-Path $pair.RepoPath) {
            $repoWrite = (Get-Item $pair.RepoPath).LastWriteTime
            if ($lastWriteRepo[$pair.Name] -ne $repoWrite) {
                $lastWriteRepo[$pair.Name] = $repoWrite
                Copy-Item $pair.RepoPath $pair.GamePath -Force
                # Update game snapshot so we don't echo it back.
                $lastWriteGame[$pair.Name] = (Get-Item $pair.GamePath).LastWriteTime
                Write-Host "  -> $($pair.Name)" -ForegroundColor Cyan
            }
        }

        # Game -> Repo: game modified a XML (e.g. export command).
        if (Test-Path $pair.GamePath) {
            $gameWrite = (Get-Item $pair.GamePath).LastWriteTime
            if ($lastWriteGame[$pair.Name] -ne $gameWrite) {
                $lastWriteGame[$pair.Name] = $gameWrite
                Copy-Item $pair.GamePath $pair.RepoPath -Force
                # Update repo snapshot so we don't echo it back.
                $lastWriteRepo[$pair.Name] = (Get-Item $pair.RepoPath).LastWriteTime
                Write-Host "  <- $($pair.Name)" -ForegroundColor Yellow
            }
        }
    }

    # items.json: game -> repo only.
    if (Test-Path $itemsJsonGamePath) {
        $currentWrite = (Get-Item $itemsJsonGamePath).LastWriteTime
        if ($lastWriteItemsJson -ne $currentWrite) {
            $lastWriteItemsJson = $currentWrite
            $itemsJsonRepoPathParent = Split-Path $itemsJsonRepoPath -Parent
            if (-not (Test-Path $itemsJsonRepoPathParent)) {
                New-Item -ItemType Directory -Path $itemsJsonRepoPathParent -Force | Out-Null
            }
            Copy-Item $itemsJsonGamePath $itemsJsonRepoPath -Force
            Write-Host "  <- items.json" -ForegroundColor Yellow
        }
    }
    Start-Sleep -Milliseconds 500
}
Write-Host "`nBannerlord exited (code $($process.ExitCode))." -ForegroundColor Green

$thumbnailSrc = Join-Path $gameModuleDataPath "item-thumbnails"
if (Test-Path $thumbnailSrc) {
    $thumbnailDst = Join-Path $repoPath "src\WebUI\public"
    if (-not (Test-Path $thumbnailDst)) {
        New-Item -ItemType Directory -Path $thumbnailDst -Force | Out-Null
    }
    Get-ChildItem $thumbnailSrc -File | ForEach-Object {
        Move-Item $_.FullName (Join-Path $thumbnailDst $_.Name) -Force
    }
    Write-Host "  item thumbnails"
}

Write-Host "`nDone." -ForegroundColor Green
