name: WebUI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      dir: ./src/WebUI
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: '22.x'
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
    - name: Install
      run: npm install
      working-directory: ${{env.dir}}
    - name: Lint
      run: npm run lint
      working-directory: ${{env.dir}}
    - name: Typecheck
      run: npm run typecheck
      working-directory: ${{env.dir}}
    - name: Unit
      run: npm run test:unit
      working-directory: ${{env.dir}}
    - name: Build
      run: npm run build
      working-directory: ${{env.dir}}
